project = "nginxdev-test"
region = "us-central1"
user = "nishikantjha0011"
email = "terraform-account@nginxdev-test.iam.gserviceaccount.com"
domain = "devopstesting.tk"
URL = "https://devopstesting.tk"